[build]
  command = "npm install && npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/waittimes"
  to = "/.netlify/functions/waittimes"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
